theme: minima
title: Jordan Waxman
description: Technical Program Manager | AI/ML Operations | Automation & Systems
show_downloads: false
google_analytics: # Add your GA tracking ID if you want analytics
